# Feature extraction

#### Loading Dataset
 - make a new column for episode count
 - make a new column for time stamp
 - which anime has the highest score
 - top 5 highest scoring anime
 - which anime has the highest score count
 - animes with top 5 episode count
 - which is the longest running anime

In [45]:
import numpy as np
import pandas as pd

In [46]:
# load the dataset
df = pd.read_csv('/Users/nittratan/ml/anime.csv')

In [47]:
df

    Rank                                              Title  Score
0      1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1      2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2      3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3      4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4      5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05
5      6  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04
6      7  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04
7      8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04
8      9  Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...   9.04
9     10  Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...   9.03
10    11  Shingeki no Kyojin: The Final Season - Kankets...   9.03
11    12  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...   9.02
12    13  Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...   8.99
13    14  Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...   8.99
14    15  Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...   8.98
15    16  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...   8.94
16    17  Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...   8.94
17    18  3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...   8.93
18    19  Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...   8.93
19    20  Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...   8.91
20    21  Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...   8.91
21    22  Violet Evergarden MovieMovie (1 eps)Sep 2020 -...   8.89
22    23  Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...   8.88
23    24  Gintama.: Shirogane no Tamashii-hen - Kouhan-s...   8.88
24    25  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...   8.87
25    26  Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...   8.84
26    27  Kaguya-sama wa Kokurasetai: First Kiss wa Owar...   8.84
27    28  Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...   8.83
28    29  The First Slam DunkMovie (1 eps)Dec 2022 - Dec...   8.83
29    30  Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...   8.82
30    31  Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...   8.82
31    32  Gintama.: Shirogane no Tamashii-henTV (12 eps)...   8.81
32    33  Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...   8.81
33    34  Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...   8.80
34    35  Shingeki no Kyojin: The Final SeasonTV (16 eps...   8.80
35    36  Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...   8.79
36    37  Kizumonogatari III: Reiketsu-henMovie (1 eps)J...   8.79
37    38  "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...   8.79
38    39  Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...   8.78
39    40  Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...   8.78
40    41  Monogatari Series: Second SeasonTV (26 eps)Jul...   8.77
41    42  Shingeki no Kyojin: The Final Season Part 2TV ...   8.77
42    43  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...   8.76
43    44  Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...   8.75
44    45  Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...   8.75
45    46  Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...   8.74
46    47  Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...   8.73
47    48  Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...   8.72
48    49  Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...   8.71
49    50  Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...   8.71

In [48]:
df.head() # return the first 5 rows of the dataframe

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [49]:
df.loc[0] # return the first row of the dataframe

Rank                                                     1
Title    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
Score                                                  9.1
Name: 0, dtype: object

In [50]:
df.loc[2]['Title'] # return the title of the third anime

'Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members'

### create a new column for episode count

In [51]:
def extract_episode(txt):
    check = False
    data = ''
    
    for i in txt:
        if i == ')':
            break
        
        if check:
            data += i
        
        if i == '(':
            check = True
            
    return data

In [52]:
df['Title'].apply(extract_episode) # apply the extract_episode function to each value in the Title column

0      64 eps
1      24 eps
2      13 eps
3      51 eps
4      10 eps
5      51 eps
6       1 eps
7     148 eps
8      13 eps
9      13 eps
10      2 eps
11    110 eps
12     13 eps
13     13 eps
14     12 eps
15    201 eps
16      1 eps
17     22 eps
18     24 eps
19     25 eps
20      1 eps
21      1 eps
22      7 eps
23     14 eps
24     74 eps
25      1 eps
26      1 eps
27     12 eps
28      1 eps
29     24 eps
30     23 eps
31     12 eps
32     26 eps
33     13 eps
34     16 eps
35     11 eps
36      1 eps
37     11 eps
38     10 eps
39      1 eps
40     26 eps
41     12 eps
42     75 eps
43     26 eps
44     26 eps
45     24 eps
46     10 eps
47     12 eps
48     12 eps
49      4 eps
Name: Title, dtype: str

In [53]:
df['Episodes'] = df['Title'].apply(extract_episode) # create a new column for episode count

In [54]:
df.head() # return the first 5 rows of the dataframe

   Rank                                              Title  Score Episodes
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10   64 eps
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07   24 eps
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06   13 eps
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06   51 eps
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05   10 eps

In [55]:
df['Episodes'].str.replace(' eps', '') # remove the ' eps' string from the Episodes column

0      64
1      24
2      13
3      51
4      10
5      51
6       1
7     148
8      13
9      13
10      2
11    110
12     13
13     13
14     12
15    201
16      1
17     22
18     24
19     25
20      1
21      1
22      7
23     14
24     74
25      1
26      1
27     12
28      1
29     24
30     23
31     12
32     26
33     13
34     16
35     11
36      1
37     11
38     10
39      1
40     26
41     12
42     75
43     26
44     26
45     24
46     10
47     12
48     12
49      4
Name: Episodes, dtype: str

In [56]:
df['Episodes'] = df['Episodes'].str.replace(' eps', '') # update the Episodes column with the cleaned values

In [57]:
df.head() # return the first 5 rows of the dataframe

   Rank                                              Title  Score Episodes
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10       64
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07       24
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06       13
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06       51
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05       10

In [58]:
type(df['Episodes'][0]) # check the data type of the first value in the Episodes column

str

In [59]:
df.loc[0]['Episodes'] # return the episode count of the first anime

'64'

In [60]:
df['Episodes'] = df['Episodes'].astype(int) # convert the Episodes column to integer data type

In [61]:
df.info() # return the summary of the dataframe, including data types and non-null counts

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Rank      50 non-null     int64
 1   Title     50 non-null     str
 2   Score     50 non-null     float64
 3   Episodes  50 non-null     int64
dtypes: float64(1), int64(2), str(1)
memory usage: 1.7 KB

### Create a new column for time stamps

In [62]:
df.loc[0]['Title'] # return the title of the first anime

'Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview'

In [63]:
import re

def extract_timestamp(txt):
    match = re.search(r'\)([A-Z][a-z]{2} \d{4} - [A-Z][a-z]{2} \d{4})', txt)
    
    if match:
        return match.group(1)
    return None

In [64]:
df['Timestamp'] = df['Title'].apply(extract_timestamp) # create a new column for timestamp

In [65]:
df.head() # return the first 5 rows of the dataframe

,Rank,Title,Score,Episodes,Timestamp
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019

In [68]:
type(df['Timestamp']) # check the data type of the first value in the Timestamp column

pandas.Series

In [69]:
# highest scoring anime
df[df['Score'] == df['Score'].max()]

,Rank,Title,Score,Episodes,Timestamp
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.1,64,Apr 2009 - Jul 2010

In [72]:
df['Score'].value_counts() # return the count of each unique value in the Score column

Score
9.04    4
8.79    3
9.06    2
9.03    2
8.99    2
8.94    2
8.93    2
8.91    2
8.88    2
8.84    2
8.83    2
8.82    2
8.81    2
8.80    2
8.78    2
8.77    2
8.75    2
8.71    2
9.10    1
9.07    1
9.05    1
9.02    1
8.98    1
8.89    1
8.87    1
8.76    1
8.74    1
8.73    1
8.72    1
Name: count, dtype: int64

In [74]:
df['Score'].unique() # return the unique values in the Score column

array([9.1 , 9.07, 9.06, 9.05, 9.04, 9.03, 9.02, 8.99, 8.98, 8.94, 8.93,
       8.91, 8.89, 8.88, 8.87, 8.84, 8.83, 8.82, 8.81, 8.8 , 8.79, 8.78,
       8.77, 8.76, 8.75, 8.74, 8.73, 8.72, 8.71])

In [76]:
df[df['Episodes'] == df['Episodes'].max()] # return the anime with the highest episode count

,Rank,Title,Score,Episodes,Timestamp
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010