## Group by Aggregation

In [1]:
import numpy as np
import pandas as pd

In [6]:
data = {
    'category': ['A', 'B', 'A', 'B', 'A','B', 'A', 'B'],
    'store': ['S1', 'S2', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'sales': [100, 150, 200, 250, 300, 350, 400, 450],
    'quantity': [10, 15, 20, 25, 30, 35, 40, 45],
    'date': pd.date_range(start='2023-01-01', periods=8, freq='D')
}
df = pd.DataFrame(data)

In [7]:
df

  category store  sales  quantity       date
0        A    S1    100        10 2023-01-01
1        B    S2    150        15 2023-01-02
2        A    S2    200        20 2023-01-03
3        B    S2    250        25 2023-01-04
4        A    S1    300        30 2023-01-05
5        B    S2    350        35 2023-01-06
6        A    S2    400        40 2023-01-07
7        B    S1    450        45 2023-01-08

In [8]:
# group by category and calculate total sales
cat =df.groupby('category')
cat

In [9]:
for name, group in cat:
    print(f"Category: {name}")
    print(group)
    print("\n")

Category: A
  category store  sales  quantity       date
0        A    S1    100        10 2023-01-01
2        A    S2    200        20 2023-01-03
4        A    S1    300        30 2023-01-05
6        A    S2    400        40 2023-01-07


Category: B
  category store  sales  quantity       date
1        B    S2    150        15 2023-01-02
3        B    S2    250        25 2023-01-04
5        B    S2    350        35 2023-01-06
7        B    S1    450        45 2023-01-08

In [10]:
cat = df.groupby('category')['sales'].sum()

In [11]:
cat

category
A    1000
B    1200
Name: sales, dtype: int64

In [13]:
df.groupby(['category', 'store'])['sales'].sum()

category  store
A         S1       400
          S2       600
B         S1       450
          S2       750
Name: sales, dtype: int64

In [14]:
# Aggregation functions
# mean, sum, count, min, max, std, var, median
df.groupby('category')['sales'].agg(['mean', 'sum', 'count', 'min', 'max', 'std', 'var', 'median'])

           mean   sum  count  min  max         std           var  median
category
A         250.0  1000      4  100  400  129.099445  16666.666667   250.0
B         300.0  1200      4  150  450  129.099445  16666.666667   300.0

In [15]:
df['sales'].mean()

np.float64(275.0)

In [17]:
df['category'].mode()

0    A
1    B
Name: category, dtype: str