## Pandas - merge, join, and concat

In [10]:
import numpy as np
import pandas as pd

In [11]:
# employees DataFrame with employee_id, Name, and Department columns
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Department': ['HR', 'IT', 'IT', 'HR', 'Finance'],
    
})

# salaries DataFrame with employee_id and Salary columns
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5, 6],  # Note that employee_id 6 does not exist in the employees DataFrame
    'Salary': [70000, 80000, 75000, 72000, 90000, 85000],
    'bonus': [5000, 6000, 5500, 5200, 7000, 6500]
})

In [12]:
employees

   employee_id     Name Department
0            1    Alice         HR
1            2      Bob         IT
2            3  Charlie         IT
3            4    David         HR
4            5      Eve    Finance

In [13]:
salaries

   employee_id  Salary  bonus
0            1   70000   5000
1            2   80000   6000
2            3   75000   5500
3            4   72000   5200
4            5   90000   7000
5            6   85000   6500

In [14]:
pd.merge(employees, salaries)

   employee_id     Name Department  Salary  bonus
0            1    Alice         HR   70000   5000
1            2      Bob         IT   80000   6000
2            3  Charlie         IT   75000   5500
3            4    David         HR   72000   5200
4            5      Eve    Finance   90000   7000

In [15]:
# Merge the employees and salaries DataFrames on employee_id
merged_data = pd.merge(employees, salaries, on='employee_id')

In [16]:
merged_data

   employee_id     Name Department  Salary  bonus
0            1    Alice         HR   70000   5000
1            2      Bob         IT   80000   6000
2            3  Charlie         IT   75000   5500
3            4    David         HR   72000   5200
4            5      Eve    Finance   90000   7000

In [17]:
pd.merge(employees, salaries, on='employee_id', how='inner')  # Default is 'inner', so this will give the same result as above

   employee_id     Name Department  Salary  bonus
0            1    Alice         HR   70000   5000
1            2      Bob         IT   80000   6000
2            3  Charlie         IT   75000   5500
3            4    David         HR   72000   5200
4            5      Eve    Finance   90000   7000

In [18]:
pd.merge(employees, salaries, on='employee_id', how='outer')  # This will include all records from both DataFrames, filling in NaN for missing values

   employee_id     Name Department  Salary  bonus
0            1    Alice         HR   70000   5000
1            2      Bob         IT   80000   6000
2            3  Charlie         IT   75000   5500
3            4    David         HR   72000   5200
4            5      Eve    Finance   90000   7000
5            6      NaN        NaN   85000   6500

In [19]:
pd.merge(employees, salaries, on='employee_id', how='left')

   employee_id     Name Department  Salary  bonus
0            1    Alice         HR   70000   5000
1            2      Bob         IT   80000   6000
2            3  Charlie         IT   75000   5500
3            4    David         HR   72000   5200
4            5      Eve    Finance   90000   7000

In [20]:
pd.merge(employees, salaries, on='employee_id', how='right')

   employee_id     Name Department  Salary  bonus
0            1    Alice         HR   70000   5000
1            2      Bob         IT   80000   6000
2            3  Charlie         IT   75000   5500
3            4    David         HR   72000   5200
4            5      Eve    Finance   90000   7000
5            6      NaN        NaN   85000   6500

## Concatination of 2 dataframes

In [28]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})
df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [29]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [30]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [31]:
pd.concat([df1, df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [33]:
pd.concat([df2, df1])

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [34]:
pd.concat([df1, df2], ignore_index=True)

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
3  A3  B3  C3
4  A4  B4  C4
5  A5  B5  C5

## Joining 2 data frames

In [35]:
df1 = pd.DataFrame({
    'name' : ['Alice', 'Bob', 'Charlie'],
}, index=[1, 2, 3])

df2 = pd.DataFrame({
    'score' : [85, 90, 95],
}, index=[2, 3, 4])

In [36]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [37]:
df2

   score
2     85
3     90
4     95

In [38]:
df1.join(df2)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [39]:
df1.join(df2, how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   95.0

In [40]:
df1.join(df2, how='inner')

      name  score
2      Bob     85
3  Charlie     90

In [41]:
df2.join(df1, how='inner')

   score     name
2     85      Bob
3     90  Charlie

In [42]:
df2.join(df1)

   score     name
2     85      Bob
3     90  Charlie
4     95      NaN