## Pivot Tables

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

In [3]:
df = pd.DataFrame(data)
df.head()

        Date Product Region  Sales  Units    Rep
0 2023-01-01       A   East    828     26   John
1 2023-01-02       B   West    814     96   Mary
2 2023-01-03       C  North    554     54    Bob
3 2023-01-04       D  South    374     54  Alice
4 2023-01-05       A   East    358     63   John

In [4]:
df

         Date Product Region  Sales  Units    Rep
0  2023-01-01       A   East    828     26   John
1  2023-01-02       B   West    814     96   Mary
2  2023-01-03       C  North    554     54    Bob
3  2023-01-04       D  South    374     54  Alice
4  2023-01-05       A   East    358     63   John
5  2023-01-06       B   West    695     64   Mary
6  2023-01-07       C  North    516     50    Bob
7  2023-01-08       D  South    379     79  Alice
8  2023-01-09       A   East    801     22   John
9  2023-01-10       B   West    181     67   Mary
10 2023-01-11       C  North    174     72    Bob
11 2023-01-12       D  South    893     93  Alice
12 2023-01-13       A   East    306     20   John
13 2023-01-14       B   West    794     38   Mary
14 2023-01-15       C  North    727     99    Bob
15 2023-01-16       D  South    740     70  Alice
16 2023-01-17       A   East    302     65   John
17 2023-01-18       B   West    911     21   Mary
18 2023-01-19       C  North    961     59    Bob
19 2023-01-20       D  South    275     39  Alice

In [5]:
df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)

In [6]:
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    828     26   John  January      Q1
1  2023-01-02       B   West    814     96   Mary  January      Q1
2  2023-01-03       C  North    554     54    Bob  January      Q1
3  2023-01-04       D  South    374     54  Alice  January      Q1
4  2023-01-05       A   East    358     63   John  January      Q1
5  2023-01-06       B   West    695     64   Mary  January      Q1
6  2023-01-07       C  North    516     50    Bob  January      Q1
7  2023-01-08       D  South    379     79  Alice  January      Q1
8  2023-01-09       A   East    801     22   John  January      Q1
9  2023-01-10       B   West    181     67   Mary  January      Q1
10 2023-01-11       C  North    174     72    Bob  January      Q1
11 2023-01-12       D  South    893     93  Alice  January      Q1
12 2023-01-13       A   East    306     20   John  January      Q1
13 2023-01-14       B   West    794     38   Mary  January      Q1
14 2023-01-15       C  North    727     99    Bob  January      Q1
15 2023-01-16       D  South    740     70  Alice  January      Q1
16 2023-01-17       A   East    302     65   John  January      Q1
17 2023-01-18       B   West    911     21   Mary  January      Q1
18 2023-01-19       C  North    961     59    Bob  January      Q1
19 2023-01-20       D  South    275     39  Alice  January      Q1

In [10]:
pd.pivot_table(df, values='Sales', index='Region', columns='Product', aggfunc='median')

Product      A      B      C      D
Region
East     358.0    NaN    NaN    NaN
North      NaN    NaN  554.0    NaN
South      NaN    NaN    NaN  379.0
West       NaN  794.0    NaN    NaN

In [11]:
pivot2 = pd.pivot_table(df, values=['Sales', 'Units'], index='Region', columns='Product')

In [12]:
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     519.0    NaN    NaN    NaN  39.2   NaN   NaN   NaN
North      NaN    NaN  586.4    NaN   NaN   NaN  66.8   NaN
South      NaN    NaN    NaN  532.2   NaN   NaN   NaN  67.0
West       NaN  679.0    NaN    NaN   NaN  57.2   NaN   NaN

In [18]:
# pd.pivot_table(df, values=['Units', 'Quarter'], index='Region', columns='Product')
# error because 'Quarter' is not numeric

In [21]:
# cross tabs
pd.crosstab(df['Region'], df['Product'])
# count of each product sold in each region

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0