## Pandas Dataframe

##### A Pandas DataFrame is a two-dimensional labeled data structure in Pandas. It is similar to a table in a database or an Excel spreadsheet, with data arranged in rows and columns.

##### Each column in a DataFrame can have a different data type, such as integers, floats, strings, or dates.

In [1]:
import numpy as np
import pandas as pd

# Creating a Dataframe

In [3]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston'],
    'salary': [50000, 60000, 70000, 80000]
}

In [4]:
data

{'Name': ['Alice', 'Bob', 'Charlie', 'David'],
 'Age': [25, 30, 35, 40],
 'City': ['New York', 'Los Angeles', 'Chicago', 'Houston'],
 'salary': [50000, 60000, 70000, 80000]}

In [5]:
pd.DataFrame(data)

      Name  Age         City  salary
0    Alice   25     New York   50000
1      Bob   30  Los Angeles   60000
2  Charlie   35      Chicago   70000
3    David   40      Houston   80000

In [6]:
df = pd.DataFrame(data)

In [7]:
df

      Name  Age         City  salary
0    Alice   25     New York   50000
1      Bob   30  Los Angeles   60000
2  Charlie   35      Chicago   70000
3    David   40      Houston   80000

In [8]:
data_list = [
    ['Alice', 25, 'New York', 50000],
    ['Bob', 30, 'Los Angeles', 60000],
    ['Charlie', 35, 'Chicago', 70000],
    ['David', 40, 'Houston', 80000]
]

In [10]:
df2 = pd.DataFrame(data_list) # index will be the default integer index and the columns will be the default integer columns

In [11]:
df

      Name  Age         City  salary
0    Alice   25     New York   50000
1      Bob   30  Los Angeles   60000
2  Charlie   35      Chicago   70000
3    David   40      Houston   80000

In [12]:
df3 = pd.DataFrame(data_list, columns=['Name', 'Age', 'City', 'Salary']) # specify column names

In [13]:
df3

      Name  Age         City  Salary
0    Alice   25     New York   50000
1      Bob   30  Los Angeles   60000
2  Charlie   35      Chicago   70000
3    David   40      Houston   80000

In [14]:
# df[0] # this will give an error because we have column names, not integer columns
df['Name'] # this will give the 'Name' column

0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: str

In [16]:
df['City'] # access a single column

0       New York
1    Los Angeles
2        Chicago
3        Houston
Name: City, dtype: str

In [17]:
df[['Name', 'Age']] # access multiple columns

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40

### creating a new Column

In [36]:
df2['Designation'] = ['Engineer', 'Manager', 'Director', 'VP'] # add a new column to df2
df2

         0   1            2      3 Designation
0    Alice  25     New York  50000    Engineer
1      Bob  30  Los Angeles  60000     Manager
2  Charlie  35      Chicago  70000    Director
3    David  40      Houston  80000          VP

### Remove column
~~~
axis=0       -> rows
axis=1       -> columns
inplace=True -> change original DataFrame
~~~

In [37]:
# df2.drop('Designation') # throw error because Designation is not an index, it's a column

In [38]:
df2.drop('Designation', axis=1) # drop the 'Designation' column from df2 
# not drop from original df2, just return a new dataframe without the 'Designation' column

         0   1            2      3
0    Alice  25     New York  50000
1      Bob  30  Los Angeles  60000
2  Charlie  35      Chicago  70000
3    David  40      Houston  80000

In [ ]:
df2.drop('Designation', axis=1, inplace=True) # drop the 'Designation' column from 
# df2 and modify df2 in place
df2

         0   1            2      3
0    Alice  25     New York  50000
1      Bob  30  Los Angeles  60000
2  Charlie  35      Chicago  70000
3    David  40      Houston  80000

### Selecting a row

In [40]:
df.loc[0] # access the first row of df2 using .loc

Name         Alice
Age             25
City      New York
salary       50000
Name: 0, dtype: object

In [41]:
df

      Name  Age         City  salary
0    Alice   25     New York   50000
1      Bob   30  Los Angeles   60000
2  Charlie   35      Chicago   70000
3    David   40      Houston   80000

In [42]:
# selecting subset of rows and columns using .loc
df.loc[0:2, ['Name', 'City']] # select rows 0 to 2 and columns 'Name' and 'City' using .loc

      Name         City
0    Alice     New York
1      Bob  Los Angeles
2  Charlie      Chicago

In [43]:
df.iloc[3] # access the fourth row of df2 using .iloc

Name        David
Age            40
City      Houston
salary      80000
Name: 3, dtype: object

In [44]:
df.loc[[0,1]][['Name', 'City']] # select rows 0 and 1 and columns 'Name' and 'City' using .loc

    Name         City
0  Alice     New York
1    Bob  Los Angeles

### conditional Selection

In [46]:
# view only those people who are older than 30
df[df['Age'] > 30] # inner condition to filter rows where 'Age' is greater than 30

      Name  Age     City  salary
2  Charlie   35  Chicago   70000
3    David   40  Houston   80000

In [ ]:
# those people who are older than 30 and live in Chicago
df[(df['Age'] > 30) & (df['City'] == 'Chicago')] # inner conditions to filter rows where 'Age' is greater than 30 and 'City' is 'Chicago'

      Name  Age     City  salary
2  Charlie   35  Chicago   70000