## Missing Data
fillna() on a selected column.
dropna() is row-wise by default.

In [1]:
import numpy as np
import pandas as pd

### Finding missing data

In [4]:
data = {
    'A': [1,2, np.nan, 4, 5],
    'B': [5, np.nan, np.nan, 8, 10],
    'C': [10, 20, 30, 40, 50],
    'D': [np.nan, 1, 2, 3, 4]
}
df = pd.DataFrame(data)

In [5]:
df

     A     B   C    D
0  1.0   5.0  10  NaN
1  2.0   NaN  20  1.0
2  NaN   NaN  30  2.0
3  4.0   8.0  40  3.0
4  5.0  10.0  50  4.0

In [6]:
df.isna() # check for missing values in the DataFrame, returns a DataFrame of the same shape with True for missing values and False for non-missing values

       A      B      C      D
0  False  False  False   True
1  False   True  False  False
2   True   True  False  False
3  False  False  False  False
4  False  False  False  False

In [7]:
df.isna().sum() # count the number of missing values in each column, returns a Series with the count of missing values for each column

A    1
B    2
C    0
D    1
dtype: int64

In [8]:
df.isna().any() # check if there are any missing values in each column, returns a Series with True for columns that have at least one missing value and False for columns that have no missing values

A     True
B     True
C    False
D     True
dtype: bool

In [9]:
df.dropna() # drop rows with any missing values, returns a new DataFrame with only the rows that have no missing values

     A     B   C    D
3  4.0   8.0  40  3.0
4  5.0  10.0  50  4.0

In [10]:
df

     A     B   C    D
0  1.0   5.0  10  NaN
1  2.0   NaN  20  1.0
2  NaN   NaN  30  2.0
3  4.0   8.0  40  3.0
4  5.0  10.0  50  4.0

In [11]:
df.dropna(thresh=3) # drop rows that have less than 3 non-missing values, returns a new DataFrame with only the rows that have at least 3 non-missing values

     A     B   C    D
0  1.0   5.0  10  NaN
1  2.0   NaN  20  1.0
3  4.0   8.0  40  3.0
4  5.0  10.0  50  4.0

### Filling the missing Data

In [12]:
df

     A     B   C    D
0  1.0   5.0  10  NaN
1  2.0   NaN  20  1.0
2  NaN   NaN  30  2.0
3  4.0   8.0  40  3.0
4  5.0  10.0  50  4.0

In [15]:
df.fillna(0) # fill missing values with 0, returns a new DataFrame with missing values replaced by 0
# not apply to original DataFrame unless you use inplace=True

     A     B   C    D
0  1.0   5.0  10  0.0
1  2.0   0.0  20  1.0
2  0.0   0.0  30  2.0
3  4.0   8.0  40  3.0
4  5.0  10.0  50  4.0

In [16]:
values = {'A': 0, 'B': df['B'].mean(), 'D': df['D'].median()} # create a dictionary with column names as keys and fill values as values
df.fillna(values) # fill missing values with specified values for each column, returns a new DataFrame with missing values replaced by the specified values for each column

     A          B   C    D
0  1.0   5.000000  10  2.5
1  2.0   7.666667  20  1.0
2  0.0   7.666667  30  2.0
3  4.0   8.000000  40  3.0
4  5.0  10.000000  50  4.0